FROM registry.fedoraproject.org/fedora-minimal

USER root

ENV HISTSIZE=10000
ENV HISTTIMEFORMAT="%d/%m/%y %T "
ENV HISTFILESIZE=20000

ENV PKGS_BASE="fzf bash-completion python3-cryptography"

ENV PKGS_GENERAL="htop \
    btop \
    sysstat \
    util-linux \
    lm_sensors \
    smartmontools \
    ffmpeg-free \
    yt-dlp \
    openfortivpn \
    conntrack-tools \
    wireguard-tools \
    iotop \
    rsync"

ENV PKGS_PROCESSES="procps-ng \
    strace"

ENV PKGS_NETWORK="bind-utils \
    nmap \
    nmap-ncat \
    telnet \
    tcpdump \
    iftop \
    iproute \
    iputils \
    whois \
    iptraf-ng \
    mtr"

RUN dnf5 install -y ${PKGS_BASE} ${PKGS_GENERAL} ${PKGS_PROCESSES} ${PKGS_NETWORK} && \
    dnf5 -y autoremove && \
    dnf5 -y clean all

COPY help-toolbox.sh /usr/bin/help-toolbox
COPY ./bin /usr/local/bin

RUN chmod 555 /usr/bin/help-toolbox && \
    echo $'[ -f /usr/share/fzf/shell/key-bindings.bash ] && source /usr/share/fzf/shell/key-bindings.bash;\
source /etc/profile.d/bash_completion.sh;\
PS1=\'[system-toolbox \W/]\$ \'\
' >> /root/.bashrc

USER root
