FROM forgejo.maciej.cloud/pkg/mc-fedora-base

ENV PKGS_BASE="python3-cryptography"

ENV PKGS_GENERAL="htop \
    btop \
    sysstat \
    util-linux \
    lm_sensors \
    smartmontools \
    ffmpeg-free \
    yt-dlp \
    openfortivpn \
    conntrack-tools \
    wireguard-tools \
    iotop \
    rsync \
    compsize"

ENV PKGS_PROCESSES="procps-ng \
    strace"

ENV PKGS_NETWORK="bind-utils \
    nmap \
    nmap-ncat \
    telnet \
    tcpdump \
    iftop \
    iproute \
    iputils \
    whois \
    iptraf-ng \
    mtr"

COPY help-toolbox.sh /usr/bin/help-toolbox

RUN dnf5 install -y ${PKGS_BASE} ${PKGS_GENERAL} ${PKGS_PROCESSES} ${PKGS_NETWORK} && \
    chmod 555 /usr/bin/help-toolbox && \
    dnf5 -y autoremove && \
    dnf5 -y clean all

COPY ./bin /usr/local/bin
