FROM forgejo.maciej.cloud/pkg/mc-fedora-base

ENV QT_QPA_PLATFORM=wayland

ENV GENERAL_PKGS="\
    iproute \
    fzf \
    wget \
    git \
    dbus \
    dbus-x11 \
    strace \
    systemd \
    NetworkManager \
    "

ENV APPS="\
    chromium \
    firefox"

# install dependencies and basic apps
RUN dnf5 install -y \
    ${GENERAL_PKGS} \
    ${APPS} \
    && dnf5 clean all

ENTRYPOINT [ "/sbin/init" ]
