FROM registry.fedoraproject.org/fedora-minimal

RUN dnf5 install -y tor nyx util-linux && \
    dnf5 clean all

COPY torrc.conf /torrc

WORKDIR /

USER toranon

ENTRYPOINT ["/usr/bin/tor", "-f", "/torrc"]
