FROM registry.fedoraproject.org/fedora-minimal:39

USER root

ENV HISTSIZE=10000
ENV HISTTIMEFORMAT="%d/%m/%y %T "
ENV HISTFILESIZE=20000

# for helm install script
ENV VERIFY_CHECKSUM="false" 

ENV PKGS_BASE="fzf git python3-pip rclone rsync bash-completion kubernetes-client golang-sigs-k8s-kustomize"
ENV PKGS_TEMP="python3-devel gcc wget tar"

RUN dnf5 install -y ${PKGS_BASE} ${PKGS_TEMP} && \
    pip3 install python-openstackclient python-swiftclient python-heatclient python-designateclient && \
    curl -o /dev/stdout https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash - && \
    dnf5 remove -y ${PKGS_TEMP} && \
    dnf5 -y autoremove && \
    dnf5 -y clean all && \
    mkdir /data

WORKDIR /data

COPY kube_ps.sh /root/kube_ps.sh

RUN echo $'[ -f /usr/share/fzf/shell/key-bindings.bash ] && source /usr/share/fzf/shell/key-bindings.bash;\
source /root/kube_ps.sh;\
PS1=\'[cloud-toolbox \W/ $(kube_ps1)]\$ \'\
' >> /root/.bashrc

ENTRYPOINT [ "/bin/bash" ]
