FROM ghcr.io/helmfile/helmfile:canary as helmfile

# ----

FROM forgejo.maciej.cloud/pkg/mc-fedora-base

# for helm install script
ENV VERIFY_CHECKSUM="false" 

ENV PKGS_BASE="git python3-pip rclone rsync kubernetes-client wget"
ENV PKGS_TEMP="python3-devel gcc tar gzip"

COPY --from=helmfile /usr/local/bin/helmfile /usr/local/bin/helmfile

RUN dnf5 install -y ${PKGS_BASE} ${PKGS_TEMP} && \
    pip3 install python-openstackclient python-swiftclient python-heatclient python-designateclient && \
    curl -o /dev/stdout https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash - && \
    rpm --nodeps -e systemd && \
    dnf5 remove -y ${PKGS_TEMP} && \
    dnf5 -y autoremove && \
    dnf5 -y clean all && \
    mkdir /data

WORKDIR /data

ENTRYPOINT [ "/bin/bash" ]
