FROM registry.fedoraproject.org/fedora-minimal

ENV TZ=Europe/Warsaw
# install also tor, for geoip data
RUN dnf5 install -y shadow-utils git golang tor && \
    useradd -u 1423 -m -s '/bin/bash' -U snowflake && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    git clone https://git.torproject.org/pluggable-transports/snowflake.git && \
    cd snowflake/proxy && \
    go build && \
    (rpm --nodeps -e systemd || true) && \
    dnf5 remove -y golang git shadow-utils && \
    dnf5 -y autoremove && \
    dnf5 -y clean all && \
    mv /snowflake/proxy/proxy /usr/bin/proxy && \
    cd / && \
    rm -rf /snowflake /root/* && \
    chown snowflake:snowflake /usr/bin/proxy

USER snowflake

ENTRYPOINT ["/usr/bin/proxy"]
